// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.example.helloworld.models.builders;

import com.example.helloworld.models.CountrySection;

public class CountrySectionBuilder extends CountrySectionBuilderBase<CountrySectionBuilder> {
    public static CountrySectionBuilder countrySection() {
        return new CountrySectionBuilder();
    }

    public CountrySectionBuilder() {
        super(new CountrySection());
    }

    public CountrySection build() {
        return getInstance();
    }
}

class CountrySectionBuilderBase<GeneratorT extends CountrySectionBuilderBase<GeneratorT>> {
    private CountrySection instance;

    protected CountrySectionBuilderBase(CountrySection aInstance) {
        instance = aInstance;
    }

    protected CountrySection getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withTitle(String aValue) {
        instance.setTitle(aValue);

        return (GeneratorT) this;
    }
}
